STAYED_COLUMN = "stayed"
LEN_STAYED_COLUMN = f"{STAYED_COLUMN}_len"

MOVED_COLUMN = "moved"
LEN_MOVED_COLUMN = f"{MOVED_COLUMN}_len"

ARRIVED_COLUMN = "arrived"
LEN_ARRIVED_COLUMN = f"{ARRIVED_COLUMN}_len"

LEN_MAPPING = {STAYED_COLUMN: LEN_STAYED_COLUMN,
               MOVED_COLUMN: LEN_MOVED_COLUMN,
               ARRIVED_COLUMN: LEN_ARRIVED_COLUMN}
